backend:
  name: github
  repo: frederickswebdesigns/website-build-test

media_folder: static/img
public_folder: img

collections:
  - name: "post"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - { name: body, label: Body, widget: markdown }
